#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR/../../"

# configure
./installers/win/build-scripts/configure.bat>>build.log 2>&1

# source env generated by configure
source .env

# build
./installers/win/build-scripts/build.bat "${PROJECT_NAME}">>build.log 2>&1
